### ISSUE TITLE
Check current browser tab for Disable rules

### ISSUE THREAD

**Issue by choco** [thompsonate/Shifty#19]
I don't want to disable Night Shift when using Safari, but I want to disable it if I'm watching Netflix in Safari. I'd be cool to use the current tab for the disable rules. Obtaining current tab url isn't an issue since most browser make this information available through Scripting Addition, but I'm not sure if there's a smarter way then just polling every arbitrary amount of time.

**Comment by thompsonate** [comment]
I wouldn't want to implement this with polling, especially since I'd have to deal with multiple browsers. Maybe the best solution would be a browser extension that sends an NSNotification, but that would take a lot of work to implement.

Probably the best solution for you, although not ideal, is to use a different browser for Netflix and set Shifty to disable for that browser. Also, customizable global keyboard shortcuts are coming in the next update, so that should make it easier to toggle manually.

**Comment by choco** [comment]
I may give this a shot if you're interested, even though my Swift knowledge is basically nothing. My idea would be to add some logic in the `updateCurrentApp` method and:

Get the current app bundle id:
1. If it matches a bundle id rules, disable Night Switch (basically the current logic)
2. if it doesn't match any bundle id rule but it matches a browser rule:
   1. try and get current tab url and check for any rule matching that 
   2. use accessibility api to setup notifications for listening on window title change
   3. when title changes, obtain the url again and check for rule again
   4. when focused app changes again, deactivate notifications

**Comment by thompsonate** [comment]
If we can get notifications on window title change, then this is exactly what we'd want to do. Feel free to give it a shot!
