### ISSUE TITLE
shifty just works on internal display but not external display when I use macbook pro 13

### ISSUE THREAD

**Issue by wheam** [thompsonate/Shifty#66]
the pictures 
https://www.instagram.com/p/Bq87CxLAq9O/?utm_source=ig_share_sheet&igshid=14in7arzyx5r

I have a Acer PE270 display, when I use my macbook pro 2017 15', shifty works fine on the external display, when I use my macbook pro 2017 13', shifty just works on internal display, I dont know why

**Comment by thompsonate** [comment]
Night Shift only supports [specific models](https://support.apple.com/en-us/HT207513#requirements) of external monitors. There may be ways to get Night Shift to work with your monitor, but I don't know enough about this issue to recommend something. Or you could use f.lux which should work since it uses its own blue light filter.

Sorry :(
