### ISSUE TITLE
Not remembering disable settings

### ISSUE THREAD

**Issue by thefella** [thompsonate/Shifty#70]
I have it disabled for programs like Photoshop, Lightroom, and VLC, but if I restart my machine, Shifty won't remember this and I have to make sure it ignores the programs all over again. I'm running 1.0.2.

**Comment by thompsonate** [comment]
That's odd. I'll look into it.

**Comment by choco** [comment]
Can you still reproduce the issue? Have you tried resetting the preferences? (when you reset them in Mojave there is a bug that forces you to restart the system before reopening the app or the preferences will get restored and can get corrupted)

**Comment by thefella** [comment]
Happens every time I restart. I've deleted the prefs file and restarted multiple times. Still won't remember the disabled programs.

**Comment by choco** [comment]
I can't reproduce it on my setup. It would really help if anyone reproducing this could upload their preferences file (`~/Library/Preferences/io.thomposnate.shifty.plist`), post the log file and try the following procedure:

1. in terminal type `defaults read io.natethompson.Shifty disabledApps`
2. save output and post it here
3. make a new app disabled
4. in terminal type again `defaults read io.natethompson.Shifty disabledApps`
5. save output again and post it here
6. restart the app and in terminal type again `defaults read io.natethompson.Shifty disabledApps`
7. post also the output of the above command

**Comment by zhumingcheng697** [comment]
> 1. in terminal type `defaults read io.natethompson.Shifty disabledApps`
> 2. save output and post it here
> 3. make a new app disabled
> 4. in terminal type again `defaults read io.natethompson.Shifty disabledApps`
> 5. save output again and post it here
> 6. restart the app and in terminal type again `defaults read io.natethompson.Shifty disabledApps`
> 7. post also the output of the above command

So I have tried these steps and there is something really interesting with the output. Every time a new app is disabled, `^fullScreenOnly_bundleIdentifier_XXX` (in hexadecimal format) is added to the pref file, as intended, and it would still be there after Shifty is relaunched. However, if I disable another app now that Shifty has been relaunched, all the previous entries get erased and this app becomes the only one that is listed in that pref file. 
 
My wild guess is that:
1. Due to some unknown reasons, Shifty cannot access its original pref file after it has been relaunched — which explains why Shifty no longer disables Night Shift for designated apps after relaunch. 

2. Although the pref file is somehow unaccessible for Shifty, it is still at where it used to be and accessible for terminal.

3. When I try to disable another app, since Shifty has failed to access its original pref file, it creates a new one at the same place, and the original one gets replaced by the new one — which explains why all the previous entries are gone and there is only the newly disabled app present.

If such is the case, we just have to figure out why Shifty cannot access its original pref file, and if this problem is solved, everything should work perfectly fine.

PS: I am using a Simplified Chinese system language, and I don't know if it has anything to do with this bug.

**Comment by thompsonate** [comment]
Okay, I figured out how to reproduce this. If you don't have _both_ browser rules _and_ app rules saved, it'll skip importing the saved preferences for the one that was saved. Just a dumb coding mistake.

Will post a binary here soon so we can make sure that fixes the issue and I'll put out an update soon.

**Comment by thompsonate** [comment]
@thefella @zhumingcheng697 If you could, please check this version and make sure it solves your issue.

[Shifty.app.zip](https://github.com/thompsonate/Shifty/files/3076816/Shifty.app.zip)

**Comment by zhumingcheng697** [comment]
@thompsonate Great, it's working now!

**Comment by thefella** [comment]
I can't check if this is working, as the new version you sent won't open/run on my Mojave beta version (10.14.5 beta). I've installed the stable version of Shifty and it works as before.

**Comment by zhumingcheng697** [comment]
@thefella I guess it’s just some signing / macOS gatekeeper issue. Use two fingers to tap on the app icon, then select “open.” This should work.

**Comment by thefella** [comment]
@zhumingcheng697 Nope, I tried that and that didn't work. I also tried deleting all files, restarting my Mac, checking permissions, and it still wouldn't open.

**Comment by zhumingcheng697** [comment]
@thefella That's weird. I worked for me back on 10.14.5 beta 1 (18F96h). Now that I've updated to the latest 10.14.5 beta 2 (18F108f), I also have no difficulties in launching Shifty.

**Comment by thompsonate** [comment]
@thefella Can you get info and check the version number? I accidentally uploaded a version that was crashing on launch, but fixed it before either of you commented.

**Comment by thefella** [comment]
@thompsonate I re-downloaded the file and it seems to be launching now! Maybe I was quick off the mark and downloaded the broken version. All seems to be good now. Good work!

**Comment by thompsonate** [comment]
Great, thanks everyone for your help!

Trying to fix a few other issues and I'll push out an update soon.
