### ISSUE TITLE
Multiple Custom Schedules for Different Color Temperatures

### ISSUE THREAD

**Issue by ioemilio** [thompsonate/Shifty#91]
What about adding multiple custom schedules in the preferences, each with custom color temperature/intensity? For example, I often find myself setting a stronger intensity at late night than that at sunset. With multiple custom schedules the change would be automatic!

It would be cool to also have relative times with respect to sunset and sunrise. For example turning NightShift on at sunset and setting it stronger after, say, two hours.

This is similar to [intensity custom curve Issue #12](https://github.com/thompsonate/Shifty/issues/12), but instead of having a gradual change in color it could be possible to set different colors at different times in the day.

This feature would somewhat emulate the behavior of flux. An example would be like the following:

Schedule1
From: Sunrise
To: Sunrise + 2h
Intensity: 50

Schedule2
From: Sunrise + 2h
To: Sunset
Intensity: 0

Schedule3
From: Sunset 
To: Sunset + 2h
Intensity: 50

Schedule4
From: Sunset + 2h 
To: Sunrise
Intensity: 100

**Comment by choco** [comment]
It's certeainly  doable, but since opening the custom curve issue #12 I learned that Night Shift has it's own intensity curve and I've grown to like it (especially since we fixed the color reset when switching based on rules). So if anyone feels like implementing this then I can provide feedback but won't be working on it myself. Also since this would be the way we'd implement custom intensity curves, I'll mark this issue as duplicate and copy-paste you message in other thread.
